### ISSUE TITLE
Incorrect paths in config

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-boneyard/wdio-selenium-standalone-service#13]
_From @monolithed on October 19, 2016 17:53_
### Config

``` js
{
   seleniumLogs: '/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cache/logs'
}
```
### Result

```
/Users/a.abashkin/workspace/mail.ru/e.mail.ru/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cache/logs
```
### Expected

```
/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cache/logs
```

![img-2016-10-19-20-52-17](https://cloud.githubusercontent.com/assets/803674/19530785/f25f782e-963d-11e6-9911-f594d51aa276.png)

_Copied from original issue: webdriverio/webdriverio#1656_

**Comment by christian-bromann** [comment]
Are you using the selenium-standalone service? If yes I think we should file the issue there.

**Comment by christian-bromann** [comment]
_From @monolithed on October 19, 2016 18:19_

Yep, selenium-standalone

**Comment by robfarr** [comment]
Should be as simple as changing:
```js
let absolutePath = path.join(process.cwd(), filePath)
```
to
```js
let absolutePath = path.resolve(filePath)
```

in [getFilePath.js](https://github.com/webdriverio/wdio-selenium-standalone-service/blob/master/lib/utils/getFilePath.js#L12).
