### ISSUE TITLE
Update Selenium Standalone?

### ISSUE THREAD

**Issue by jeremyrajan** [webdriverio-boneyard/wdio-selenium-standalone-service#15]
Hi,

Could we please look at updating the selenium version. The current version is [5.11.0](https://github.com/vvo/selenium-standalone) (in package 5.6.0) and has few good things in it, including updated drivers :).

cc @christian-bromann 

Thanks,
Jeremy

**Comment by christian-bromann** [comment]
@jeremyrajan the version is defined with `^5.6.0` so it will automatically install `5.11.0`
