### ISSUE TITLE
We need to update selenium stand alone to ^6.0.0

### ISSUE THREAD

**Issue by axelhildingson** [webdriverio-boneyard/wdio-selenium-standalone-service#16]
It is simple fix to make it possible to run test on firefox 51

**Comment by axelhildingson** [comment]
@christian-bromann, do you have time? i tried to make a PR but I don't have permission .

**Comment by christian-bromann** [comment]
@axelhildingson you need to fork the repo first and then make a PR

**Comment by psylence303** [comment]
+1 would love it

**Comment by axelhildingson** [comment]
https://github.com/webdriverio/wdio-selenium-standalone-service/pull/17
