### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by michaelryancaputo** [webdriverio-boneyard/wdio-selenium-standalone-service#18]
I see there was a release over the last few days, but I don't see anywhere a Changelog describing those changes. Since we're using this in production, would be nice to get an idea of what has changed.

Thanks

**Comment by christian-bromann** [comment]
@michaelryancaputo we just updated the selenium-standalone package. I haven't made any changelogs as there are not many changes here. So my changelog is basically the commit log. I will make a changelog file with the next release.
