### ISSUE TITLE
No installing new chromedriver still executes 2.27

### ISSUE THREAD

**Issue by sshaar08** [webdriverio-boneyard/wdio-selenium-standalone-service#20]
services: ['selenium-standalone'],
    seleniumLogs: './',
    seleniumArgs: {
        platform: 'MAC',
    },
    seleniumInstallArgs: {
        chrome: {
            version: '2.28',
            arch: process.arch,
            baseURL: 'https://chromedriver.storage.googleapis.com'
        },

        version: '3.3.0',
    },

**Comment by christian-bromann** [comment]
Please file issue here: https://github.com/vvo/selenium-standalone
