### ISSUE TITLE
Installing a specific version of Selenium

### ISSUE THREAD

**Issue by maximilianschmitt** [webdriverio-boneyard/wdio-selenium-standalone-service#31]
Hi, I would like to install and use a specific version of Selenium because it seems like this might solve my problem of random `SocketException`s occurring with macOS: https://github.com/Codeception/CodeceptJS/issues/687#issuecomment-325674646

What would the correct configuration look like to achieve the equivalent of this...

```
selenium-standalone install --version=3.4.0
selenium-standalone start --version=3.4.0
```

...?

Thanks for your help!

Best,
Max

**Comment by christian-bromann** [comment]
Please raise this feature request in the [selenium-standalone](https://github.com/vvo/selenium-standalone) project. Thanks!

**Comment by maximilianschmitt** [comment]
Hi @christian-bromann, thanks for taking a look!

This issue is not about `selenium-standalone`, it's about how to configure `wdio-selenium-standalone-service` to provide the `--version` arguments to `selenium-standalone` when installing / starting.

I had a look at the README section for [options](https://github.com/webdriverio/wdio-selenium-standalone-service#options) but this throws errors for me:

```
$ wdio-build
server is running on port 65291
A service failed in the 'onPrepare' hook
Error: Selenium server did not start.
Another Selenium process may already be running or your java version may be out of date.
Be sure to check the official Selenium release notes for minimum required java version: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

    at ChildProcess.errorIfNeverStarted (~/code/node_modules/selenium-standalone/lib/start.js:158:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Continue...
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
Error: connect ECONNREFUSED 127.0.0.1:4444
```

These are the configurations I tried, both fail for me:

1)

```javascript
{
  services: ["selenium-standalone"],
  seleniumArgs: {
    seleniumArgs: ["--version", "3.4.0"]
  },
  seleniumInstallArgs: {
    version: "3.4.0"
  }
}
```

2)

```javascript
{
  services: ["selenium-standalone"],
  seleniumArgs: {
    seleniumArgs: ["--version", "3.4.0"]
  },
  seleniumInstallArgs: {
    '--version': '3.4.0'
  }
}
```

It runs when I remove both `seleniumArgs` and `seleniumInstallArgs` but then I get regular `"java.net.SocketException: Connection reset by peer (connect failed)"`.

Any idea what would be going wrong? Thanks for your help!

**Comment by leabaertschi** [comment]
@maximilianschmitt the following is working for me:
```
seleniumInstallArgs: { version: '3.4.0' },
seleniumArgs: { version: '3.4.0' },
```

but you need to make sure to delete the installed selenium server from your node_modules in order for it to get installed again when running the test runner. Look for `.selenium` folder in your node_modules and delete it.
