### ISSUE TITLE
Always calling install / support offline mode

### ISSUE THREAD

**Issue by mkj28** [webdriverio-boneyard/wdio-selenium-standalone-service#32]
Feature request.

Looks like wdio-selenium-standalone-service always calls `selenium-standalone install`, but if you already have the drivers downloaded, and don't have Internet, `start` is all you need.

It is related (and looks like other part of work) is https://github.com/vvo/selenium-standalone/issues/265

**Comment by christian-bromann** [comment]
I think this work should be done in the selenium-standalone package.
