### ISSUE TITLE
"Actions" dont work on Firefox with ver 0.0.10

### ISSUE THREAD

**Issue by pi4r0n** [webdriverio-boneyard/wdio-selenium-standalone-service#45]
Hey guys, I have noticed that **actions** aren't working when I use you package. Please note that when I run selenium-server-standalone-3.11.0 and point to to gecko driver the same action work perfectly fine.

`[
			{
				"type": "pointer",
				"id": "finger1",
				"parameters": {"pointerType": "mouse"},
				"actions": [
					{ "type": "pointerMove", "duration": 0, "x": location.x + xOffset, "y": location.y + yOffset },
				],
			},
		]`

I have attached some logs for you guys
[selenium-standalone.txt](https://github.com/webdriverio/wdio-selenium-standalone-service/files/1836536/selenium-standalone.txt)

**Comment by christian-bromann** [comment]
This is not an issue of the wdio-selenium-standalone-service. You probably downloaded an outdated geckodriver version. You can change this in the configurations. If you have further questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!
