### ISSUE TITLE
log issues

### ISSUE THREAD

**Issue by zinserjan** [webdriverio-boneyard/wdio-selenium-standalone-service#5]
First of all thanks for this great project. This makes testing with selenium in different browsers much easier :)

Unfortunately, I found a few issues with the `seleniumLogs` option:
1. it's not possible to specify a file path. Only directories are supported, otherwise the file will be created as directory if it doesn't exist yet (see [L61](https://github.com/webdriverio/wdio-selenium-standalone-service/blob/955480e369fc0608e23836648cb14a4657150b8d/lib/launcher.js#L61)).
2. seleniumLogs fails on windows caused by a wrong path separator check (see [L64](https://github.com/webdriverio/wdio-selenium-standalone-service/blob/955480e369fc0608e23836648cb14a4657150b8d/lib/launcher.js#L64))
3. it should handle absolute paths

I'm happy to submit a PR to fix these issues.

**Comment by christian-bromann** [comment]
Let's continue conversation on this in #6
