### ISSUE TITLE
What is the purpose of wdio-selenium-standalone-service?

### ISSUE THREAD

**Issue by Taewa** [webdriverio-boneyard/wdio-selenium-standalone-service#61]
Hi,
I am not sure if I understand properly the concept of `wdio-selenium-standalone-service`.

When I reboot my laptop, I have to execute `selenium-standalone start` in order to be able to start wdio test.

However, I thought if I use `wdio-selenium-standalone-service`, then I don't have to run manually `selenium-standalone start` whenever I test with wdio.

Is this wrong?

Thanks.

**Comment by christian-bromann** [comment]
> Is this wrong?

Nope. That is the reason why this service exists.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
