### ISSUE TITLE
Couldn't initialise "@wdio/selenium-standalone-service".

### ISSUE THREAD

**Issue by vitaly87** [webdriverio-boneyard/wdio-selenium-standalone-service#62]
Hi all
I am using selenium-standalone as service , 
my conf looks like

```
  plugins: {
       wdio: {
         enabled: true,
         services: ['selenium-standalone']
         // additional config for service can be passed here
       },
```
the error 

> Could not load plugin wdio from module './plugin/wdio':
> Couldn't initialise "@wdio/selenium-standalone-service".
> Error: Cannot find module '@wdio/logger'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
>     at Module.require (internal/modules/cjs/loader.js:636:17)

**Comment by christian-bromann** [comment]
Fixing it.
