### ISSUE TITLE
Do not start a server for remote hosts

### ISSUE THREAD

**Issue by monolithed** [webdriverio-boneyard/wdio-selenium-standalone-service#8]
It would be nice to have an additional option to exclude the `selenium-standalone` service from `services` for remote hosts or something like:

``` js
onPrepare (options) {
    let { host, services = [] } = options;

    if (!/127\.0\.0\.1|localhost|::1/.test(host)) {
        let index = services.includes('selenium-standalone');

        if (index) {
            options.services.splice(index, 1);
        }
    }
}
```

**Comment by christian-bromann** [comment]
Why do you want to do that in the onPrepare hook. You can tweak the service list depending of the host in your config already since it is a normal js file.

**Comment by monolithed** [comment]
I don't want use the onPrepare hook for that )

> You can tweak the service list depending of the host in your config already since it is a normal js file.

Could you provide an example? 
I tried to pass the `services` to the Launcher and that did not work for me.

**Comment by christian-bromann** [comment]
something like that:

``` js
// wdio.conf.js
exports.config = {
  // ...
}

if (!/127\.0\.0\.1|localhost|::1/.test(exports.config.host)) {
    let index = exports.config.services.includes('selenium-standalone');

    if (index) {
        exports.config.services.splice(index, 1);
    }
}
```

However I don't know how you've setup WebdriverIO.

**Comment by monolithed** [comment]
Hm, I guess it will work, thanks!
